# Generated by Django 2.2.2 on 2019-06-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190618_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summar',
            new_name='summary',
        ),
    ]
